### ISSUE TITLE
Design home page and photo gallery

### ISSUE THREAD

**Issue by tonyhieu** [tonyhieu/p4-oompaloompas#18]
Finished creating base design. [Color scheme](https://github.com/tonyhieu/p4-oompaloompas/blob/master/static/css/default.css) and [home page layout](https://github.com/tonyhieu/p4-oompaloompas/blob/master/templates/index.html) created.

**Comment by LindaLiu1202** [comment]
Add another arrow to the button of the home page. If you click on it, you will be taking to another page with pics of a different theme (maybe a black & white theme).
