### ISSUE TITLE
Teacher Week 4 Review

### ISSUE THREAD

**Issue by tonyhieu** [tonyhieu/p4-oompaloompas#26]

**Comment by jm1021** [comment]
Reviewed issues.  Some member not present with technical acivity.  .9/1.0

**Comment by jm1021** [comment]
Individually, the review in video was very strong.   Looking at Issues most of links to evidence except Ellen.  I decided to review individual commits from scrum board and saw that all the comments and change lists were meaningful tasks. 
2.0/2.0 for everyone

**Comment by jm1021** [comment]
Team planning.  Seems like you are missing the concept of Time Box capturing project history week over week.  The Review column was well structured and Issues made sense and contained links.  .9/1.0 holds

Team work.  Tasks seem to be very independent and somewhat random, Anthony's squares and Sanvi's CSS seem like prototypes, but without README or some other vision it is lost on me.  Also, your pages look very inconsistent in demo and many are very plain.  Hard to see what vision of project is anymore.  1.85/2

**Comment by jm1021** [comment]
Score is 4.5 for everyone.  I am looking for some cohesiveness in next week.
