### ISSUE TITLE
Week 7 Work

### ISSUE THREAD

**Issue by sanvi1855544** [tonyhieu/p4-oompaloompas#51]
1.75/2 Mr. M said lack of secondary thinking

**Comment by jm1021** [comment]
Starting to see a few designs that look a little better.  Glad to see Linda involved, but she needs to make better quality videos on next lab or it will be major deduction.   A little overlap and I am not clear which labs you want graded.  I really liked style where first two or three did demo and code side by side.  7.5 of 8
